# Generated by Django 4.2.16 on 2024-10-30 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('category_color', models.CharField(choices=[('#FF0000', 'Red'), ('#00FF00', 'Green'), ('#0000FF', 'Blue'), ('#FFFF00', 'Yellow'), ('#FF00FF', 'Magenta'), ('#00FFFF', 'Cyan'), ('#000000', 'Black'), ('#FFFFFF', 'White')], default='#FFFFFF', max_length=7)),
            ],
        ),
    ]
