# Generated by Django 5.1.2 on 2024-10-30 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_note_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='category_color',
            new_name='category_colour',
        ),
    ]
