# Generated by Django 5.1.2 on 2024-11-01 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='title',
            field=models.CharField(default='Untitled', max_length=50),
        ),
    ]
